
services:
  # Servizio CPU
  ocr-api-cpu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocr-api-cpu
    ports:
      - "9292:9292"
    volumes:
      - .:/app
      - paddle_models_cpu:/root/.paddle
      - paddleocr_models_cpu:/root/.paddleocr
    environment:
      - DEVICE=cpu
    restart: unless-stopped


volumes:
  paddle_models_cpu:
  paddleocr_models_cpu:
