version: '3.8'

services:
  # Servizio CPU
  paddleocr-api-cpu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paddleocr-api-cpu
    ports:
      - "9292:9292"
    volumes:
      - .:/app
      - paddle_models_cpu:/root/.paddle
      #- paddle_models_cpu:/home/appuser/.paddle:rw
      - paddleocr_models_cpu:/root/.paddleocr
      #- paddleocr_models_cpu:/home/appuser/.paddleocr:rw
    environment:
      - DEVICE=cpu
    restart: unless-stopped


volumes:
  paddle_models_cpu:
  paddleocr_models_cpu:
